spring:
    flyway:
        url: jdbc:postgresql://10.203.92.253:5432/pg_keycloak
        user: postgres
        password: postgres
        enabled: true
        locations: classpath:/database/migration/
        baseline-on-migrate: true
        schemas: public
    datasource:
        username: postgres
        password: postgres
        url: jdbc:postgresql://10.203.92.253:5432/pg_keycloak
        driver-class-name: org.postgresql.Driver

keycloak:
    realm: docsearch
    auth-server-url: http://localhost:9443/auth
    ssl-required: external
    resource: docsearch-app
    use-resource-role-mappings: true
    bearer-only: true
    principal-attribute: preferred_username
    credentials:
        secret: 04aaadf3-97df-45c4-aa35-bbec7535ceeb

admin:
    panel:
        realm: master
        resource: admin-cli
        login: admin
        password: admin

logging:
    file:
        name: doc-search.log
    level:
        org:
            zalando:
                logbook: trace
logbook:
    include:
        - /**
    #  exclude:
    #    - /admin-panel/**
    filter.enabled: true
    format.style: json
    strategy: default
    obfuscate:
        headers:
            - postman-token
            - Authorization
            - X-Secret
        parameters:
            - access_token
            - password
    write:
        chunk-size: 1000
