spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/ds_keycloak_db
    user: postgres
    password: postgres21!
    enabled: true
    locations: classpath:/database/migration/
    baseline-on-migrate: true
    schemas: public
  keycloak-datasource:
    username: postgres
    password: postgres21!
    url: jdbc:postgresql://localhost:5432/ds_keycloak_db
    driver-class-name: org.postgresql.Driver
  storage-datasource:
    username: postgres
    password: postgres21!
    url: jdbc:postgresql://localhost:5433/ds_storage_db
    driver-class-name: org.postgresql.Driver

password-reset:
  expiration-time: 36000000

keycloak:
  realm: docsearch
  auth-server-url: http://localhost:9443/auth
  ssl-required: external
  resource: docsearch-app
  use-resource-role-mappings: true
  bearer-only: true
  principal-attribute: preferred_username
  credentials:
    secret: 04aaadf3-97df-45c4-aa35-bbec7535ceeb

admin:
  panel:
    realm: master
    resource: admin-cli
    login: admin
    password: admin

logging:
  file:
    name: doc-search.log
  level:
    org:
      zalando:
        logbook: trace
logbook:
  include:
    - /**
  filter.enabled: true
  format.style: json
  strategy: default
  obfuscate:
    headers:
      - postman-token
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    chunk-size: 1000
